name: Release
on:
  push:
    branches: ["release"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Test
        run: make test
      - name: Build
        run: make build
      - name: Get version
        id: version
        run: echo "version=$(cat ./VERSION)" >> $GITHUB_OUTPUT
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./smc
          allowUpdates: false
          artifactErrorsFailBuild: true
          name: ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          body: |
            Automated release build from `release` branch.
